<?php

include("../code/connection.php");


if ($_SESSION['last_id']=="") {
    # code...
                    echo "<script>window.location='../service.php';</script>";
}
 $apiKey = "rzp_test_Wi972bG7df7ltY";

// $id=$_SESSION['book_id'];
// $sql = "SELECT * FROM `services` where id=$id"; 
// $run = mysqli_query($con, $sql);
 
//                             $row = mysqli_fetch_assoc($run);
//                             extract($row); 

 
?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="invoice.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_SESSION['price'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Online Water Supplies"
    data-name="water Supply"
    data-description="Online water supplies"
    data-prefill.name="<?php echo $_SESSION['name']; ?>"
    data-prefill.email="water@gmil.com"
    data-prefill.contact="<?php echo $_SESSION['mobile'] ?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style type="text/css">
    .razorpay-payment-button{
        display: none;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.razorpay-payment-button').click();
    });
</script>